# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
inhibit_all_warnings!

target 'WeathersamaDemo' do
    pod 'Weathersama', :path => '~/documents/icaksama/GIT/Weathersama/Weathersama'
end
