# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target ‘Weathersama’ do
  pod 'Alamofire', '~> 4.5'
end
